master:
  datasource:
    url: jdbc:mysql://localhost:3306/masterDB?characterEncoding=UTF-8&userSSL=false
    username: root
    password: admin123
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/clusterDB?characterEncoding=UTF-8&userSSL=false
    username: root
    password: admin123
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
logging:
  level:
    root: info
    com.yyq.data.master.repository: debug
    com.yyq.data.master.web: info

