spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clusterDB?characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2b8
    username: root
    password: admin123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  context-path: /sell/